<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
             xmlns:xs="http://www.w3.org/2001/XMLSchema"
             xmlns:wsdp="http://schemas.xmlsoap.org/ws/2006/02/devprof"
             xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
             xmlns:wsd="http://schemas.xmlsoap.org/ws/2005/04/discovery"
             xmlns:wse="http://schemas.xmlsoap.org/ws/2004/08/eventing"
             xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"
             xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
             xmlns:wprt11="http://schemas.microsoft.com/windows/2010/06/wdp/printv11"
             targetNamespace="http://schemas.microsoft.com/windows/2010/06/wdp/printv11"
             name="WSDPrinterServiceV11">

    <xs:annotation>
        <xs:documentation>
            WSD Printer Service V1.1 Extensions Web Service Description (WSDL) file
            Copyright (c) Microsoft Corporation. All rights reserved
        </xs:documentation>
    </xs:annotation>

    <wsp:Policy wsu:Id="ServicePolicy">
        <wsdp:Profile />
    </wsp:Policy>

    <types>
        <xs:schema targetNamespace="http://schemas.microsoft.com/windows/2010/06/wdp/printv11">
            <xs:include schemaLocation="WDPPrintv11.xsd"/>
        </xs:schema>
    </types>
    
</definitions>
