// <Include>
///////////////////////////////////////////////////////////////////////////////
//
// THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT MODIFY IT BY HAND.
//
///////////////////////////////////////////////////////////////////////////////
// </Include>

// <Include>
#pragma once
// </Include>

// <CDATA>

class CPrinterServiceTypeProxy;
class CPrinterServiceTypeEventSource;
class CPrinterServiceV12TypeProxy;
class CPrinterServiceV20TypeProxy;
class CPrinterServiceV20TypeEventSource;

// </CDATA>

// <EventSourceBuilderDeclarations>
HRESULT CreateCPrinterServiceTypeEventSource(IWSDDeviceHost* pHost, LPCWSTR pszServiceId, CPrinterServiceTypeEventSource** ppEventSourceOut);
// </EventSourceBuilderDeclarations>

// <CDATA>

class CPrinterServiceTypeEventSource: public IPrinterServiceTypeEventNotify
{
protected:
    ~CPrinterServiceTypeEventSource();
    LONG m_cRef;
    IWSDDeviceHost* m_host;
    const WCHAR* m_serviceId;

public:
    HRESULT STDMETHODCALLTYPE Init(IWSDDeviceHost* pIWSDDeviceHost, const WCHAR* serviceId);
    CPrinterServiceTypeEventSource();

// </CDATA>

// <IUnknownDeclarations>
    // 
    // IUnknown
    // 
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void **ppvObject);
    ULONG STDMETHODCALLTYPE AddRef();
    ULONG STDMETHODCALLTYPE Release();
// </IUnknownDeclarations>

// <FunctionDeclarations>
    HRESULT STDMETHODCALLTYPE
    PrinterElementsChangeEvent
    (   /* [in] */ PRINTER_ELEMENTS_CHANGE_EVENT_TYPE* body
    );

    HRESULT STDMETHODCALLTYPE
    PrinterStatusSummaryEvent
    (   /* [in] */ PRINTER_STATUS_SUMMARY_EVENT_TYPE* body
    );

    HRESULT STDMETHODCALLTYPE
    PrinterStatusConditionEvent
    (   /* [in] */ PRINTER_STATUS_CONDITION_EVENT_TYPE* body
    );

    HRESULT STDMETHODCALLTYPE
    PrinterStatusConditionClearedEvent
    (   /* [in] */ PRINTER_STATUS_CONDITION_CLEARED_EVENT_TYPE* body
    );

    HRESULT STDMETHODCALLTYPE
    JobStatusEvent
    (   /* [in] */ JOB_STATUS_EVENT_TYPE* body
    );

    HRESULT STDMETHODCALLTYPE
    JobEndStateEvent
    (   /* [in] */ JOB_END_STATE_EVENT_TYPE* body
    );

// </FunctionDeclarations>

// <CDATA>

};

// </CDATA>

// <EventSourceBuilderDeclarations>
HRESULT CreateCPrinterServiceV20TypeEventSource(IWSDDeviceHost* pHost, LPCWSTR pszServiceId, CPrinterServiceV20TypeEventSource** ppEventSourceOut);
// </EventSourceBuilderDeclarations>

// <CDATA>

class CPrinterServiceV20TypeEventSource: public IPrinterServiceV20TypeEventNotify
{
protected:
    ~CPrinterServiceV20TypeEventSource();
    LONG m_cRef;
    IWSDDeviceHost* m_host;
    const WCHAR* m_serviceId;

public:
    HRESULT STDMETHODCALLTYPE Init(IWSDDeviceHost* pIWSDDeviceHost, const WCHAR* serviceId);
    CPrinterServiceV20TypeEventSource();

// </CDATA>

// <IUnknownDeclarations>
    // 
    // IUnknown
    // 
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void **ppvObject);
    ULONG STDMETHODCALLTYPE AddRef();
    ULONG STDMETHODCALLTYPE Release();
// </IUnknownDeclarations>

// <FunctionDeclarations>
    HRESULT STDMETHODCALLTYPE
    PrintDeviceCapabilitiesChangeID
    (   /* [in] */ const WCHAR* body
    );

// </FunctionDeclarations>

// <CDATA>

};

// </CDATA>

